AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.1
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "bin/**/*"
    - "node_modules/**/*"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
